export const exercisesData = [
  {
    name: 'Reverse this',
    description: 'Implement function which reverse input of type string. Function should verify if type of argument is string. If it\'s not a type of string throw error',
    input: 'Hello world!',
    output: 'dlrow olleH!',
    solution: 'My own code',
  },
  {
    name: 'Validation',
    description: 'Implement function which reverse input of type string. Function should verify if type of argument is string. If it\'s not a type of string throw error',
    input: 'Hello world!',
    output: 'dlrow olleH!',
    solution: 'My own code',
  },
  {
    name: 'Interleaved',
    description: 'Implement function which reverse input of type string. Function should verify if type of argument is string. If it\'s not a type of string throw error',
    input: 'Hello world!',
    output: 'dlrow olleH!',
    solution: 'My own code',
  },
  {
    name: 'Predicate',
    description: 'Implement function which reverse input of type string. Function should verify if type of argument is string. If it\'s not a type of string throw error',
    input: 'Hello world!',
    output: 'dlrow olleH!',
    solution: 'My own code',
  },
  {
    name: 'Pangram',
    description: 'Implement function which reverse input of type string. Function should verify if type of argument is string. If it\'s not a type of string throw error',
    input: 'Hello world!',
    output: 'dlrow olleH!',
    solution: 'My own code',
  },
  {
    name: 'In two steps',
    description: 'Implement function which reverse input of type string. Function should verify if type of argument is string. If it\'s not a type of string throw error',
    input: 'Hello world!',
    output: 'dlrow olleH!',
    solution: 'My own code',
  },
  {
    name: 'Emoji',
    description: 'Implement function which reverse input of type string. Function should verify if type of argument is string. If it\'s not a type of string throw error',
    input: 'Hello world!',
    output: 'dlrow olleH!',
    solution: 'My own code',
  },
  {
    name: 'Duration time',
    description: 'Implement function which reverse input of type string. Function should verify if type of argument is string. If it\'s not a type of string throw error',
    input: 'Hello world!',
    output: 'dlrow olleH!',
    solution: 'My own code',
  },
  {
    name: 'Factory',
    description: 'Implement function which reverse input of type string. Function should verify if type of argument is string. If it\'s not a type of string throw error',
    input: 'Hello world!',
    output: 'dlrow olleH!',
    solution: 'My own code',
  },
  {
    name: 'The one to rule them all',
    description: 'Implement function which reverse input of type string. Function should verify if type of argument is string. If it\'s not a type of string throw error',
    input: 'Hello world!',
    output: 'dlrow olleH!',
    solution: 'My own code',
  },
  {
    name: 'Thing inside the box',
    description: 'Implement function which reverse input of type string. Function should verify if type of argument is string. If it\'s not a type of string throw error',
    input: 'Hello world!',
    output: 'dlrow olleH!',
    solution: 'My own code',
  },
  {
    name: 'Mr. Eliot',
    description: 'Implement function which reverse input of type string. Function should verify if type of argument is string. If it\'s not a type of string throw error',
    input: 'Hello world!',
    output: 'dlrow olleH!',
    solution: 'My own code',
  },
  {
    name: 'Izogram',
    description: 'Implement function which reverse input of type string. Function should verify if type of argument is string. If it\'s not a type of string throw error',
    input: 'Hello world!',
    output: 'dlrow olleH!',
    solution: 'My own code',
  },
  {
    name: 'Hashtags',
    description: 'Implement function which reverse input of type string. Function should verify if type of argument is string. If it\'s not a type of string throw error',
    input: 'Hello world!',
    output: 'dlrow olleH!',
    solution: 'My own code',
  },
  {
    name: 'Array functions',
    description: 'Implement function which reverse input of type string. Function should verify if type of argument is string. If it\'s not a type of string throw error',
    input: 'Hello world!',
    output: 'dlrow olleH!',
    solution: 'My own code',
  },
  {
    name: 'Count the words',
    description: 'Implement function which reverse input of type string. Function should verify if type of argument is string. If it\'s not a type of string throw error',
    input: 'Hello world!',
    output: 'dlrow olleH!',
    solution: 'My own code',
  },
  {
    name: 'Anagram',
    description: 'Implement function which reverse input of type string. Function should verify if type of argument is string. If it\'s not a type of string throw error',
    input: 'Hello world!',
    output: 'dlrow olleH!',
    solution: 'My own code',
  },
  {
    name: 'Verify ISBN',
    description: 'Implement function which reverse input of type string. Function should verify if type of argument is string. If it\'s not a type of string throw error',
    input: 'Hello world!',
    output: 'dlrow olleH!',
    solution: 'My own code',
  },
  {
    name: 'Brockets to fit',
    description: 'Implement function which reverse input of type string. Function should verify if type of argument is string. If it\'s not a type of string throw error',
    input: 'Hello world!',
    output: 'dlrow olleH!',
    solution: 'My own code',
  },
  {
    name: 'Flat board',
    description: 'Implement function which reverse input of type string. Function should verify if type of argument is string. If it\'s not a type of string throw error.',
    input: 'Hello world!',
    output: 'dlrow olleH!',
    solution: 'My own code',
  },
  {
    name: 'HTML String',
    description: 'Implement function which reverse input of type string. Function should verify if type of argument is string. If it\'s not a type of string throw error.',
    input: 'Hello world!',
    output: 'dlrow olleH!',
    solution: 'My own code',
  },
  {
    name: 'Anagram',
    description: 'Implement function which reverse input of type string. Function should verify if type of argument is string. If it\'s not a type of string throw error.',
    input: 'Hello world!',
    output: 'dlrow olleH!',
    solution: 'My own code',
  },
  {
    name: 'Caesar cipher',
    description: 'Implement function which reverse input of type string. Function should verify if type of argument is string. If it\'s not a type of string throw error.',
    input: 'Hello world!',
    output: 'dlrow olleH!',
    solution: 'My own code',
  },
  {
    name: 'Verify Card',
    description: 'Implement function which reverse input of type string. Function should verify if type of argument is string. If it\'s not a type of string throw error.',
    input: 'Hello world!',
    output: 'dlrow olleH!',
    solution: 'My own code',
  },
  {
    name: 'Abstract Syntax Trees',
    description: 'Implement function which reverse input of type string. Function should verify if type of argument is string. If it\'s not a type of string throw error.',
    input: 'Hello world!',
    output: 'dlrow olleH!',
    solution: 'My own code',
  },

]